### ISSUE TITLE
Basic user account

### ISSUE THREAD

**Issue by peterkapena** [peterkapena/globetalk-back#6]
**Basic account**
- 40 minutes length meeting
- Limit of 6 users
- No live translation

**Comment by peterkapena** [comment]
@andreKiona can you test this and notice how i added code in the back end to do this. You can post a question here and I will try to explain otherwise, you can set up a meeting

**Comment by andreKiona** [comment]
User Limitation works fine after testing it. Please advise if the 40 minutes length meeting was also implemented or if i should work on it

**Comment by andreKiona** [comment]
A clear explanations on the backend would also help

**Comment by peterkapena** [comment]
> User Limitation works fine after testing it. Please advise if the 40 minutes length meeting was also implemented or if i should work on it

No, yo can work on this. Try your best to implement this in the back end and not the front end.

**Comment by peterkapena** [comment]
> A clear explanations on the backend would also help

You can setup a meeting for today at 10 pm but please have a list of questions to ask. I was showing you how things are linked up in the back end on Monday do you could ask questions but you were not following

**Comment by andreKiona** [comment]
noted. i will set the meeting for 10pm

**Comment by andreKiona** [comment]
Is there anything more to be added on this task?
It seems to completed to me. kindly advise.

**Comment by peterkapena** [comment]
No, it can be closed
